# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimformTagBProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimformTagBProject
  pod 'R.swift'
  pod 'Bagel', '~>  1.3.2'
  pod 'Alamofire', '~>  4.8.2' # For Api call
  pod 'ReachabilitySwift'
  pod 'SSAppUpdater', '~> 1.1.1'
  pod 'SSSpinnerButton', '~> 3.0.2' # Button rounded animations.
  pod 'IQKeyboardManager'
  pod 'IQKeyboardManagerSwift', '~> 6.3.0' # Allows you to prevent this issue of keyboard sliding up and covering UITextField/UITextView.
  pod 'SwiftMessages'
end
